// Frontend/src/Components/CurrCard.tsx
import React from "react";

type Props = {
  title?: string;
  value?: string;
  subtext?: string;
  Time?: string;
  valueColor?: string;
  subtextColor?: string;
  extra?: string;
  extraColor?: string;
};

const StatCard: React.FC<Props> = ({
  title = "",
  value = "",
  subtext = "",
  Time = "",
  valueColor = "#ffffff",
  subtextColor = "#ffffff",
  extra = "",
  extraColor = "#ffffff",
}) => {
  return (
    <div className="bg-[#1b2330] rounded-2xl p-6 w-[300px] shadow-[0_0_10px_rgba(0,0,0,0.3)]">
      <div className="text-white text-base font-semibold mb-2">{title}</div>
      <div className="text-2xl font-bold" style={{ color: valueColor }}>
        {value}
      </div>
      <div className="mt-1 text-sm" style={{ color: subtextColor }}>
        {subtext}
      </div>
      <div className="text-xs text-gray-400 mt-2">Updated: {Time}</div>
      {extra && (
        <div className="text-sm mt-4" style={{ color: extraColor }}>
          {extra}
        </div>
      )}
    </div>
  );
};

export default StatCard;

// Frontend/src/components/CurrCard.svelte
<script>
  export let title = "";
  export let value = "";
  export let subtext = "";
  export let Time = "";
  export let valueColor = "#ffffff";
  export let subtextColor = "#ffffff";
  export let extra = "";
  export let extraColor = "#ffffff";
</script>

<style>
  .card {
    background-color: #1b2330;
    border-radius: 1rem;
    padding: 1.5rem;
    width: 300px;
    box-shadow: 0 0 10px rgba(0,0,0,0.3);
  }

  .title {
    font-size: 1rem;
    font-weight: 600;
    color: white;
    margin-bottom: 0.5rem;
  }

  .value {
    font-size: 2rem;
    font-weight: bold;
  }

  .subtext {
    margin-top: 0.3rem;
    font-size: 0.9rem;
  }

  .timestamp {
    font-size: 0.75rem;
    color: #9ca3af;
    margin-top: 0.5rem;
  }

  .extra {
    font-size: 0.85rem;
    margin-top: 1rem;
  }
</style>

<div class="card">
  <div class="title">{title}</div>
  <div class="value" style="color: {valueColor}">{value}</div>
  <div class="subtext" style="color: {subtextColor}">{subtext}</div>
  <div class="timestamp">Updated: {Time}</div>
  {#if extra}
    <div class="extra" style="color: {extraColor}">{extra}</div>
  {/if}
</div>
